approve_label: 'approved'
problem_label: 'needs some work'

allowed_targets: ['maintenance', 'devel', 'staging/maintenance', 'staging/devel']
forbidden_sources: ['master', 'maintenance', 'devel']

labels:
  docs:
    additional_allowed_targets: ['main', 'master']
  meta:
    additional_allowed_targets: ['main', 'master']
  ci/cd:
    additional_allowed_targets: ['main', 'master']

check_can_modify: true
create_review: true
