name: "Linkify systeminfo bundles"
on:
  issue_comment:
    types: [created]

jobs:
  linkifyBundles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = context.payload.comment.body;
            const bundleRegex = /\[(octoprint-systeminfo-\d{14}\.zip)\]\(([^)]+)\)/g;

            const bundles = [];
            const matches = comment.matchAll(bundleRegex);
            for (const match of matches) {
              bundles.push({filename: match.group(1), link: match.group(2)});
            };

            if (bundles) {
              let text = "I found the following bundles:\n\n";
              bundles.forEach((bundle) => {
                text += "  * [" + bundle.filename + "](https://bundleviewer.octoprint.org/?url=" + encodeURIComponent(bundle.link) + ")"
              });

              github.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: text
              });
            }
