name: "Check for bundle"
on:
  issues:
    types: ["opened", "edited"]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: OctoPrint/actions/check-for-bundle@main
      id: check
      with:
        body: ${{ github.event.issue.body }}
    - uses: OctoPrint/actions/comment-or-delete@main
      with:
        issue: ${{ github.event.issue.number }}
        marker: "<!-- comment_bundle_missing -->"
        body: |
          Hi @${{ github.event.issue.user.login }}!


          It looks like you didn't upload a [system info bundle]() as requested by the template.
          A bundle is required to further process your issue. It contains important logs and
          system information to be able to put your issue into context and give pointers as to
          how it happened.


          Please upload a bundle in your issue - no cloud links please, the data needs to be
          available right in the issue. Otherwise your issue will be closed.

          Thank you for your collaboration.
          <!-- comment_bundle_missing -->
        condition: ${{ !steps.check.outputs.result }}