name: "Check for bundle"
on:
  issues:
    types: ["opened", "edited"]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v5
      env:
        REMINDER: >
          Hi @${{ github.event.issue.user.login }}!


          It looks like you didn't upload a [system info bundle](https://community.octoprint.org/t/29887) as requested by the template.
          A bundle is required to further process your issue. It contains important logs and
          system information to be able to put your issue into context and give pointers as to
          what has happened.


          Please upload a bundle zip file to the original issue post. Actually upload the file please and 
          do not paste some link to a cloud provider, we want to have everything in one place here. 
          

          Without the availability of a bundle, your issue will have to be closed.


          Thank you for your collaboration.
        THANKYOU: >
          Thank you @${{ github.event.issue.user.login }} for adding a bundle! Now this can actually get looked at.
      with:
        script: |
          const { REMINDER, THANKYOU } = process.env;
          const bundleRegex = /\[(octoprint-systeminfo-\d{14}\.zip)\]\(([^)]+)\)/g;
          const marker = "<!-- check_for_bundle -->";

          const issueLabels = await github.rest.issues.listLabelsOnIssue({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number
          });
          const labels = issueLabels.map(label => label.name);

          if (!labels.includes("bug")) {
            return;
          }

          const comments = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          })
          const comment = comments.data.find(c => c.user.login === "github-actions[bot]" && c.body.includes(marker));

          const found = !!context.payload.issue.body.match(bundleRegex);

          if (!found) {
            const text = REMINDER + "\n" + marker;
            if (comment && comment.body !== text) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: comment.id,
                body: text
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: text
              });
            }
          } else if (found && comment) {
            const text = REMINDER.split("\n\n").map(line => `~~${line.trim()}~~`).join("\n\n") + "\n\n" + THANKYOU + "\n" + marker;
            if (comment.body !== text) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: comment.id,
                body: text
              });
            }
          }
